import turtle

turtle.setup(width=700,height=600)
turtle.speed=(10)
turtle.pensize(3)
turtle.penup()

turtle.penup()
turtle.goto(-250,-50)
turtle.setheading(60)
turtle.pendown()
turtle.begin_fill()
turtle.color("blue")
turtle.circle(40,steps=3)
turtle.end_fill()

turtle.penup()
turtle.setheading(45)
turtle.goto(-150,-50)
turtle.pendown()
turtle.begin_fill()
turtle.color("yellow")
turtle.circle(40,steps=4)
turtle.end_fill()

turtle.penup()
turtle.setheading(36)
turtle.goto(-50,-50)
turtle.pendown()
turtle.begin_fill()
turtle.color("black")
turtle.circle(40,steps=5)
turtle.end_fill()

turtle.penup()
turtle.setheading(30)
turtle.goto(50,-50)
turtle.pendown()
turtle.begin_fill()
turtle.color("pink")
turtle.circle(40,steps=6)
turtle.end_fill()

turtle.penup()
turtle.setheading(22.5)
turtle.goto(150,-50)
turtle.pendown()
turtle.begin_fill()
turtle.color("purple")
turtle.circle(40,steps=8)
turtle.end_fill()

turtle.hideturtle()
turtle.done()